Example: sample
kse-ua/Review pull request #10
Opened 2021-12-17 19:07 UTC by tshemsedinov

2021-12-22 09:53 UTC, Selbonyka commented on Tasks/sample.js
> +};
This function could be broken up into two:
```
const pickRandomNumber = (length) => {
    return Math.floor(Math.random() * length);
};

const takeSample = (...args) => {
    return (args = args[pickRandomNumber(args.length)]);
};
```

2021-12-22 09:55 UTC, Selbonyka commented on Tasks/sample.js
> +  ]; return arr
If the code won't be broken up into two functions for some reason, at least these lines should be optimised:
```
const SAMPLE = (arr) => {
  return (arr = arr[Math.floor(Math.random() * arr.length)]);
};
```

2021-12-22 09:58 UTC, Selbonyka requested changes
I have optimized this code, breaking it up into different functions, making them inline. As well now the code supports inputting individual numbers/words, so it doesn't have to take input as an array.


```js
// Get one random element from array

const pickRandomNumber = (length) => Math.floor(Math.random()*length);

const takeSample = (...args) => args[pickRandomNumber(args.length)];

const result = takeSample(123, 456, 789, 222, 333, 444);
console.log(result);

```

2021-12-22 10:59 UTC, Selbonyka commented
In case the commit doesn't work, here's this code on python:

```
import random

trial_list = [123, 456, 789, 222, 333, 444]
sample = random.choice(trial_list)
print(sample)
```

2021-12-22 12:22 UTC, Selbonyka commented on Tasks/sample.js
> +const SAMPLE = arr => {
camelCase should be used instead of CAPS

2021-12-22 12:25 UTC, Selbonyka commented on Tasks/sample.js
> +  arr = arr[
The way it's formatted isn't optimal.

2021-12-23 15:41 UTC, Selbonyka commented on Tasks/sample.js
> +    Math.floor(Math.random()* arr.length)
Since we aren't working with huge numbers, it's better to use ~~ instead of Math.floor, as it is faster

2021-12-24 11:46 UTC, tshemsedinov commented
- Use strict mode
- You can't call function before declaration
- Prefer not to use ~~

2021-12-24 11:46 UTC, closed without merging