Example: merge
kse-ua/Review pull request #29
Opened 2021-12-21 15:50 UTC by tshemsedinov

2021-12-21 17:52 UTC, YaroslavKSE requested changes
In overall I improved naming here, used Cammelcase insted of snakecase. Olso deleted some useless lines, used new structers insted of them.

2021-12-21 17:52 UTC, YaroslavKSE commented on Tasks/merge.js
> +merge_two_objects=(function merge_two_objects(object_1,object_2){
We should better use :  const mergeTwoObjects = (firstObject, secondObject) =>

2021-12-21 17:52 UTC, YaroslavKSE commented on Tasks/merge.js
> +    object_3 = [({})][0];
To create empty object in Js we use: let mergedObject = {};

2021-12-21 17:52 UTC, YaroslavKSE commented on Tasks/merge.js
> +   for (attribute_name in object_1) {
To better understanding I prefer to use: for (let object1Key in firstObject)

2021-12-21 17:52 UTC, YaroslavKSE commented on Tasks/merge.js
> +       );
We don't need this lines here

2021-12-21 17:52 UTC, YaroslavKSE commented on Tasks/merge.js
> +        object_3[attribute_name] = object_1[attribute_name]
Improved naming: mergedObject[object1Key] = firstObject[object1Key]

2021-12-21 17:52 UTC, YaroslavKSE commented on Tasks/merge.js
> +   for (attribute_name in object_2) {
Ditto

2021-12-21 17:52 UTC, YaroslavKSE commented on Tasks/merge.js
> +      (object_3[attribute_name] == object_2[attribute_name])
Don't need this line

2021-12-21 17:52 UTC, YaroslavKSE commented on Tasks/merge.js
> +     object_3[attribute_name] = object_2[attribute_name]
Improved naming: mergedObject[object2Key] = secondObject[object2Key]

2021-12-21 17:52 UTC, YaroslavKSE commented on Tasks/merge.js
> +return object_1, object_2, object_3;
We don't need to return three objects as we are creating new one: return mergedObject;

2021-12-21 17:52 UTC, YaroslavKSE commented on Tasks/merge.js
> +})
We need to finish function's body using:  };

2021-12-22 07:14 UTC, YaroslavKSE commented
```Js
const mergeTwoObjects = (firstObject, secondObject) => {
    let mergedObject = {};
    for (let object1Key in firstObject) {
        mergedObject[object1Key] = firstObject[object1Key]
    }
    for (let object2Key in secondObject) {
        mergedObject[object2Key] = secondObject[object2Key]
    }
    return mergedObject;
};

const result = mergeTwoObjects({ a: 'uno', b: 'due' }, { c: 'tre' });
console.log(result)
```

2021-12-22 07:37 UTC, YaroslavKSE commented
```py
def merge_two_dicts(first_dict, second_dict):
    merged_dict = {}
    merged_dict.update(first_dict), merged_dict.update(second_dict)
    return merged_dict


result = merge_two_dicts({'one': 1, 'two': 2}, {'name': 'Yaroslav'})
print(result)
```

2021-12-23 22:46 UTC, tshemsedinov commented
Use const instead of let

2021-12-24 07:15 UTC, YaroslavKSE commented
> Use const instead of let

Fixed

2021-12-24 09:37 UTC, closed without merging