Example: password
kse-ua/Review pull request #6
Opened 2021-12-17 18:44 UTC by tshemsedinov

2021-12-20 12:32 UTC, roflmyrlok commented
#15

2021-12-22 08:02 UTC, roflmyrlok requested changes

2021-12-22 11:31 UTC, roflmyrlok commented
```py

#Generate random password python translated
import random
import random

def generate_password(length_of_password):
  key = []
  for i in range(length_of_password):
    key.append(random.choice(characters))
  result = ''.join(key)
  return result

characters = ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', '!', '@', '#', '$', '%', '^', '&', '*']
result = generate_password(8)
print(result)

```

2021-12-22 11:33 UTC, roflmyrlok commented on Tasks/password.js
> +let GeneratePassword = ( alphabet , length ) => {
```suggestion
const generatePassword = (alphabet, length) => {
```

2021-12-22 11:35 UTC, roflmyrlok commented
```py
import random

def generate_password(length_of_password):
  key = []
  for i in range(length_of_password):
    key.append(random.choice(characters))
  result = ''.join(key)
  return result


characters = ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', '!', '@', '#', '$', '%', '^', '&', '*']
result = generate_password(8)
print(result)
```

2021-12-22 11:41 UTC, roflmyrlok commented
```js
// Generate random password fixed

const generatePassword = (lengthOfPassword) => {
  let key = [];
  for (let i = 0; i < lengthOfPassword; i++) {
    key.push(characters[Math.floor(Math.random() * characters.length)]);
  }
  return key.join("");
};

const characters = [
  "0",
  "1",
  "2",
  "3",
  "4",
  "5",
  "6",
  "7",
  "8",
  "9",
  "a",
  "b",
  "c",
  "d",
  "e",
  "f",
  "g",
  "h",
  "i",
  "j",
  "k",
  "l",
  "m",
  "n",
  "o",
  "p",
  "q",
  "r",
  "s",
  "t",
  "u",
  "v",
  "w",
  "x",
  "y",
  "z",
  "A",
  "B",
  "C",
  "D",
  "E",
  "F",
  "G",
  "H",
  "I",
  "J",
  "K",
  "L",
  "M",
  "N",
  "O",
  "P",
  "Q",
  "R",
  "S",
  "T",
  "U",
  "V",
  "W",
  "X",
  "Y",
  "Z",
  "!",
  "@",
  "#",
  "$",
  "%",
  "^",
  "&",
  "*",
];
const result = generatePassword(8);
console.log(result);

```

2021-12-24 08:58 UTC, tshemsedinov commented
- Please extract random to separate function
- Use const

2021-12-24 08:59 UTC, roflmyrlok commented
```js
// Generate random password fixed
const random = (max) => Math.floor(Math.random() * max);

const generatePassword = (lengthOfPassword) => {
  const key = [];
  for (let i = 0; i < lengthOfPassword; i++) {
    const randomChar = characters[random(characters.length)]
    key.push(randomChar);
  }
  return key.join("");
};


    
const characters = [
  "0",
  "1",
  "2",
  "3",
  "4",
  "5",
  "6",
  "7",
  "8",
  "9",
  "a",
  "b",
  "c",
  "d",
  "e",
  "f",
  "g",
  "h",
  "i",
  "j",
  "k",
  "l",
  "m",
  "n",
  "o",
  "p",
  "q",
  "r",
  "s",
  "t",
  "u",
  "v",
  "w",
  "x",
  "y",
  "z",
  "A",
  "B",
  "C",
  "D",
  "E",
  "F",
  "G",
  "H",
  "I",
  "J",
  "K",
  "L",
  "M",
  "N",
  "O",
  "P",
  "Q",
  "R",
  "S",
  "T",
  "U",
  "V",
  "W",
  "X",
  "Y",
  "Z",
  "!",
  "@",
  "#",
  "$",
  "%",
  "^",
  "&",
  "*",
];
const result = generatePassword(8);
console.log(result);
```

2021-12-24 08:59 UTC, closed without merging