Example: random
kse-ua/Review pull request #7
Opened 2021-12-17 18:45 UTC by tshemsedinov

2021-12-19 22:33 UTC, tshemsedinov commented
@vnikiforova Here is your task, please see invitation to organization kse-ua in email to have access to this repo for review

2021-12-22 09:10 UTC, vnikiforova requested changes
Change code style:
1. Add space before square bracket and remove ;
2. Split the string
3. Remove two ;
4. Add space before bracket and remove ;

2021-12-22 09:10 UTC, vnikiforova commented on Tasks/random.js
> +    ;} else {;
```suggestion
    } else {
```
Remove two ;

2021-12-22 09:10 UTC, vnikiforova commented on Tasks/random.js
> +};
```suggestion
  }
```
Add space before bracket and remove ;

2021-12-24 08:39 UTC, vnikiforova commented
```js
function between(min, max) {  
  return Math.floor(
    Math.random() * (max - min + 1) + min
  )
}

console.log(between(1, 9))
```

2021-12-24 08:40 UTC, vnikiforova commented
```py
import random


def random_num(min_n, max_n):
    print(random.randint(min_n, max_n))


random_num(1, 10)
```

2021-12-24 12:06 UTC, closed without merging